In [10]:
import json
import pandas as pd
from pathlib import Path


path = '../data/raw/latest_films.json' 
with open(path) as f:
    data = json.load(f)
        

df = pd.json_normalize(data["results"])
        
df.head()

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/6YjnTRBz704LF1uJ3ZC4wsS9T8r.jpg,"[28, 80, 53]",1290821,en,Shelter,A man living in self-imposed exile on a remote...,456.7785,/buPFnHZ3xQy6vZEHxbHgL1Pc6CR.jpg,2026-01-28,Shelter,False,6.733,206
1,False,/hYgUkH7TusddHRtelj53I6gFOWR.jpg,"[28, 53]",799882,en,The Bluff,When her tranquil life on a remote island is s...,313.8760,/sojEzvfxR2DBcDSJyAisX8TWjov.jpg,2026-02-17,The Bluff,False,6.150,163
2,False,/bAFnjhweXxHUWjmFzMTuX12Ud3b.jpg,[53],1199193,en,Pose,"Isolated in a grand country manor, a reclusive...",294.3508,/qhyyyWrHUbl6QG4udAJj17CBa5.jpg,2026-02-25,Pose,False,7.600,15
3,False,/huW5dZywslw6muqmpDtMl6Ywl3m.jpg,[35],10156,en,History of the World: Part I,An uproarious version of history that proves n...,234.2480,/6iAl78qZHT65erPXr2YW6Y54wlY.jpg,1981-06-12,History of the World: Part I,False,6.761,885
4,False,/hz7TdCrpLLt2Dz7S3PS2HG9rpAO.jpg,"[27, 9648, 80]",1159559,en,Scream 7,When a new Ghostface killer emerges in the qui...,210.7572,/jjyuk0edLiW8vOSnlfwWCCLpbh5.jpg,2026-02-25,Scream 7,False,5.993,215

In [23]:
cols_to_drop = [
    "adult",
    "backdrop_path",
    "original_title",
    "poster_path"
]

d = df.drop(cols_to_drop, axis=1)
d["release_date"] = pd.to_datetime(d["release_date"])
d = d.sort_values(by="release_date")
d.head()

,genre_ids,id,original_language,overview,popularity,release_date,title,video,vote_average,vote_count
3,[35],10156,en,An uproarious version of history that proves n...,234.2480,1981-06-12,History of the World: Part I,False,6.761,885
16,"[16, 35, 10751, 14, 12]",1497970,zh,The iconic cat-and-mouse duo accidentally trav...,118.8257,2025-08-02,Tom and Jerry: Forbidden Compass,False,4.792,12
8,"[28, 80, 53]",1461181,en,In an undisclosed area of Texas after two adop...,180.2125,2025-08-15,Hierarchy,False,5.708,12
15,"[28, 80, 18, 53]",1419406,zh,Macau Police brings the tracking expert police...,133.5331,2025-08-16,The Shadow's Edge,False,7.247,460
7,[28],1499984,en,Two brothers compete in the world's deadliest ...,189.0051,2025-08-22,Gladiator Underground,False,6.500,12

In [ ]:
import pandas as pd
import sqlite3

# load csv
df = pd.read_csv("data.csv")

# create in-memory database
conn = sqlite3.connect(":memory:")

# send dataframe to SQL
df.to_sql("table1", conn, index=False)

# run SQL query
query = """
SELECT name, age
FROM table1
WHERE age > 25
"""

result = pd.read_sql(query, conn)

print(result)